=== BeteMachine/Projet_Licence/WS_2023/CV_1.dtd
<!ELEMENT CV ((header, summary, (experience | education ), (education | experience), langues?, skills, loisir?))>
    <!ELEMENT header (name, email, address?)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT address (#PCDATA)>
    <!ELEMENT summary (summary_headline, summary_description)>
    <!ELEMENT summary_headline (#PCDATA)>
    <!ELEMENT summary_description (#PCDATA)>
    <!ELEMENT experience (job+)>
    <!ELEMENT job (job_title, job_company, job_dates, job_description*)>
    <!ELEMENT job_title (#PCDATA)>
    <!ELEMENT job_company (#PCDATA)>
    <!ELEMENT job_dates (#PCDATA)>
    <!ELEMENT job_description (#PCDATA)>
    <!ELEMENT education (degree+)>
    <!ELEMENT degree (degree_title, degree_mention?, degree_institution, degree_dates?)>
    <!ELEMENT degree_title (#PCDATA)>
    <!ELEMENT degree_mention (#PCDATA)>
    <!ELEMENT degree_institution (#PCDATA)>
    <!ELEMENT degree_dates (#PCDATA)>
    <!ELEMENT langues (langue+)>
    <!ELEMENT langue (#PCDATA)>
    <!ELEMENT skills (skill+)>
    <!ELEMENT skill (#PCDATA)>
    <!ELEMENT loisir (activite*)>
    <!ELEMENT activite (#PCDATA)>
	<!ATTLIST CV
          xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation CDATA #FIXED "CV_1.xsd">

=== BeteMachine/Projet_Licence/WS_2023/CV_1Alex.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Skeleton with CV_1.xsd (schema) -->
<!DOCTYPE CV SYSTEM "CV_1.dtd">
<CV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CV_1.xsd">
<header>
    <name>Maricic Alexandre</name>
    <email>maricic.alexandre@gmail.com</email>
    <address>Drancy</address>
</header>
  <summary>
    <summary_headline>L3 Étudiant</summary_headline>
    <summary_description>Étudiant en L3 Informatique a l'université Sorbonne Paris Nord.</summary_description>
  </summary>
  <experience>
    <job>
      <job_title>Stage</job_title>
      <job_company>Mairie de Drancy</job_company>
      <job_dates>Dec. 2014 - Janv. 2015</job_dates>
      <job_description>Assistant technicien.</job_description>
    </job>
  </experience>
  <education>
    <degree>
      <degree_title>BAC</degree_title>
      <degree_institution>Lycée Eugène Delacroix</degree_institution>
      <degree_dates>2018</degree_dates>
    </degree>
    <degree>
      <degree_title>Licence</degree_title>
      <degree_institution>Université Sorbonne Paris Nord</degree_institution>
      <degree_dates>2018-présent</degree_dates>
    </degree>
  </education>
  <langues>
  	<langue>Anglais - Niveau C1</langue>
  	<langue>Serbe - Langue maternelle</langue>
  	<langue>Espagnol - Niveau A2</langue>
  </langues>
  <skills>
    <skill>C</skill>
    <skill>HTML</skill>
    <skill>CSS</skill>
    <skill>JavaScript</skill>
    <skill>Python</skill>
    <skill>SQL</skill>
  </skills>
  <loisir>
    <activite>Basketball</activite>
    <activite>Auto-Mobile</activite>
  </loisir>
</CV>

=== BeteMachine/Projet_Licence/WS_2023/CV_2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- CV: https://www.cadremploi.fr/editorial/conseils/modeles/exemple-de-cv-de-technicien-informatique -->
<!-- Skeleton with CV_1.xsd (schema) -->
<!DOCTYPE CV SYSTEM "CV_1.dtd">
<CV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CV_1.xsd">
	<header>
		<name>Jérôme Pelai</name>
		<email>hello@reallygreatsite.com</email>
		<address>Engcobo</address>
	</header>
	<summary>
		<summary_headline>Technicien Informatique</summary_headline>
		<summary_description>7 ans d'expérience en tant que technicien informatique auprès de publics variés... </summary_description>
	</summary>
	<education>
		<degree>
			<degree_title>DUT Informatique</degree_title>
			<degree_institution>IUT de Sceaux</degree_institution>
		</degree>
		<degree>
			<degree_title>BAC Pro Systèmes electroniques numériques</degree_title>
			<degree_institution>Lycée Jean Moulin</degree_institution>
		</degree>
	</education>
	<experience>
		<job>
			<job_title>Technicien informatique</job_title>
			<job_company>ProTech</job_company>
			<job_dates>Nov. 2018 - Présent</job_dates>
			<job_description>Gestion de projets transverses.</job_description>
            <job_description>Gestion de l'Active Directory.</job_description>
            <job_description>Gestion des sauvegardes sur Robot ou lecteur DAT.</job_description>
		</job>
		<job>
			<job_title>Technicien maintenance informatique itinérant</job_title>
			<job_company>PROSERVIA</job_company>
			<job_dates>Janv. 2015 - Nov 2018</job_dates>
			<job_description>Maintenance matériel informatique.</job_description>
            <job_description>Support aux utilisateurs..</job_description>
            <job_description>Prise en main à distance et sur place.</job_description>
		</job>
	</experience>
	<skills>
		<skill>Installation et configuration des postes utilisateurs</skill>
		<skill>Prise en main à distance</skill>
		<skill>RIS, WDS, MDT</skill>
		<skill>HTML/CSS</skill>
		<skill>LAN, WAN, ADSL ...</skill>
		<skill>Connaissances en environnement virtuel</skill>
	</skills>
    <loisir>
        <activite>Internet</activite>
        <activite>Sport</activite>
        <activite>Musique</activite>
        <activite>Mots croisés</activite>
        <activite>Voyages</activite>
    </loisir>
</CV>

=== BeteMachine/Projet_Licence/WS_2023/CV_1Kev.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Skeleton with CV_1.xsd (schema) -->
<!DOCTYPE CV SYSTEM "CV_1.dtd">
<CV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CV_1.xsd">
	<header>
		<name>CHEN Kévin</name>
		<email>chen.kevin1@hotmail.com</email>
		<address>Drancy</address>
	</header>
	<summary>
		<summary_headline>Étudiant L3 Informatique</summary_headline>
		<summary_description>Étudiant en L3 Informatique à l'université Sorbonne Paris Nord.</summary_description>
	</summary>
	<education>
		<degree>
			<degree_title>Licence</degree_title>
			<degree_institution>Université Sorbonne Paris Nord</degree_institution>
			<degree_dates>2018-present</degree_dates>
		</degree>
		<degree>
			<degree_title>BAC S Option SVT</degree_title>
			<degree_mention>Assez Bien</degree_mention>
			<degree_institution>Lycée Eugène Delacroix</degree_institution>
			<degree_dates>2018</degree_dates>
		</degree>
	</education>
	<experience>
		<job>
			<job_title>Serveur en restauration</job_title>
			<job_company>Royal Buffet - Moulins</job_company>
			<job_dates>juillet - septembre 2019</job_dates>
			<job_description>Service et responsable des approvisionnements.</job_description>
		</job>
		<job>
			<job_title>Serveur en restauration</job_title>
			<job_company>Royal Buffet - Toulouse</job_company>
			<job_dates>juin - septembre 2018</job_dates>
			<job_description>Service et entretien des lieux.</job_description>
		</job>
		<job>
			<job_title>Vendeur en magasin</job_title>
			<job_company>P.A. Style - Drancy</job_company>
			<job_dates>2016 - présent</job_dates>
			<job_description>Assistance régulière en magasin de prêt à porter</job_description>
		</job>
	</experience>
	<langues>
		<langue>Anglais - Niveau C1</langue>
		<langue>Mandarin - Langue maternelle</langue>
		<langue>Espagnol - Niveau A2</langue>
	</langues>
	<skills>
		<skill>C</skill>
		<skill>SQL</skill>
		<skill>Java</skill>
		<skill>HTML/CSS</skill>
		<skill>JavaScript</skill>
		<skill>Python</skill>
	</skills>
	<loisir>
		<activite>Casse-tête</activite>
		<activite>Escalade</activite>
		<activite>Tir à l'arc</activite>
	</loisir>
</CV>

=== BeteMachine/Projet_Licence/WS_2023/CV_3.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- CV: https://www.cadremploi.fr/editorial/conseils/modeles/exemple-de-cv-dassistant-comptable -->
<!-- Skeleton with CV_1.xsd (schema) -->
<!DOCTYPE CV SYSTEM "CV_1.dtd">
<CV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CV_1.xsd">
	<header>
		<name>Jérôme Flavin</name>
		<email>jérômeflavin@monmail.fr</email>
	</header>
	<summary>
		<summary_headline>Assistant Comptable</summary_headline>
		<summary_description>Titulaire d'un Brevet de Technicien Supérieur en Comptabilité... </summary_description>
	</summary>
	<education>
		<degree>
			<degree_title>BTS Compatabilité</degree_title>
			<degree_institution>Lycée de Condorcet</degree_institution>
		</degree>
		<degree>
			<degree_title>BAC ES</degree_title>
            <degree_mention>Bien</degree_mention>
			<degree_institution>Lycée Jean Moulin</degree_institution>
            <degree_dates>2017</degree_dates>
		</degree>
	</education>
	<experience>
		<job>
			<job_title>Assistant Compatable</job_title>
			<job_company>Comptarecherche</job_company>
			<job_dates>Sept. 2019 - Présent</job_dates>
			<job_description>Travail avec des feuilles de calcul.</job_description>
            <job_description>Préparation des comptes statutaires.</job_description>
            <job_description>Calcul et vérification paiement.</job_description>
		</job>
		<job>
			<job_title>Assistant Comptable (Alternance)</job_title>
			<job_company>BNP</job_company>
			<job_dates>Sept. 2018 - Aout 2019</job_dates>
			<job_description>Suivi de la comptabilité.</job_description>
            <job_description>Gestion et suivi des factures.</job_description>
            <job_description>Suivi des dossiers de comptabilité des TPEs et PMEs.</job_description>
		</job>
	</experience>
	<skills>
		<skill>Bilan Comptable</skill>
		<skill>Calcul et déclaration</skill>
		<skill>Fiscalité des entreprises</skill>
		<skill>Traitement de facture</skill>
	</skills>
</CV>
